# Generated by Django 6.0.1 on 2026-01-12 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('item_class', models.CharField(choices=[('weapon', 'Weapon'), ('armour', 'Armour'), ('accessory', 'Accessory'), ('jewel', 'Jewel'), ('flask', 'Flase'), ('other', 'Other')], default='other', max_length=20)),
                ('slot', models.FloatField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('required_level', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('flavour_text', models.TextField(blank=True, default='')),
                ('raw_mods', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uniques', to='catalog.baseitem')),
            ],
        ),
    ]
