# Generated by Django 6.0.1 on 2026-01-13 02:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueItemLeaguePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateField(default=django.utils.timezone.now)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_presence', to='catalog.league')),
                ('unique_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_presence', to='catalog.uniqueitem')),
            ],
            options={
                'indexes': [models.Index(fields=['league', 'last_seen_at'], name='catalog_uni_league__18c5df_idx'), models.Index(fields=['unique_item', 'league'], name='catalog_uni_unique__eb10ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('unique_item', 'league'), name='uniq_uniqueitem_league')],
            },
        ),
    ]
