# Generated by Django 6.0.1 on 2026-01-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_league_uniqueitemleaguepresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='slot',
            field=models.FloatField(blank=True, default='', max_length=100, null=True),
        ),
    ]
