# Generated by Django 6.0.1 on 2026-01-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_baseitem_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueitem',
            name='poe_ninja_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
