# Generated by Django 6.0.1 on 2026-01-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_uniqueitem_poe_ninja_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueitem',
            name='poe_ninja_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
