# Generated by Django 6.0.1 on 2026-01-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_uniqueitem_poe_ninja_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
