# Generated by Django 6.0.1 on 2026-01-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_uniqueitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='slot',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
