# Generated by Django 6.0.1 on 2026-01-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_baseitem_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='item_class',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armour', 'Armour'), ('accessory', 'Accessory'), ('jewel', 'Jewel'), ('flask', 'Flask'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='slot',
            field=models.CharField(choices=[('helmet', 'Helmet'), ('body', 'Body Armour'), ('gloves', 'Gloves'), ('boots', 'Boots'), ('shield', 'Shield'), ('weapon', 'Weapon'), ('belt', 'Belt'), ('ring', 'Ring'), ('amulet', 'Amulet'), ('jewel', 'Jewel'), ('flask', 'Flask'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
