# Generated by Django 4.2.27 on 2026-01-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_league_updated_at_alter_baseitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='baseitem',
            index=models.Index(fields=['item_class', 'slot'], name='catalog_bas_item_cl_001a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='baseitem',
            index=models.Index(fields=['name'], name='catalog_bas_name_193aa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='baseitem',
            constraint=models.UniqueConstraint(fields=('name', 'item_class'), name='uniq_baseitem_name_class'),
        ),
    ]
