# Generated by Django 4.2.27 on 2026-01-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_baseitem_id_alter_league_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueitem',
            name='poe_ninja_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
