# Generated by Django 4.2.27 on 2026-01-13 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_assert_no_null_poe_ninja_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueItemLeagueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaos_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('divine_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('listing_count', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, default='', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('last_fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_stats', to='catalog.league')),
                ('unique_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_stats', to='catalog.uniqueitem')),
            ],
            options={
                'indexes': [models.Index(fields=['league', 'chaos_value'], name='catalog_uni_league__ad1fa8_idx'), models.Index(fields=['league', 'listing_count'], name='catalog_uni_league__7e76b1_idx'), models.Index(fields=['unique_item', 'league'], name='catalog_uni_unique__c994f0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='uniqueitemleaguestats',
            constraint=models.UniqueConstraint(fields=('unique_item', 'league'), name='uniq_uniqueitem_league_stats'),
        ),
    ]
