# Generated by Django 6.0.1 on 2026-02-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_uniqueitemleaguestats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueitem',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
