# Generated by Django 6.0.1 on 2026-02-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_uniqueitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
