# Generated by Django 6.0.1 on 2026-02-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_baseitem_icon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueAncientMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.CharField(choices=[('Belt', 'belt')], db_index=True, max_length=20)),
                ('tiers', models.CharField(blank=True, max_length=10, null=True)),
                ('chance', models.FloatField(blank=True, null=True)),
                ('avg_orbs', models.IntegerField(blank=True, null=True)),
                ('min_ilvl', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ancient_meta', to='catalog.uniqueitem')),
            ],
        ),
    ]
