# Generated by Django 6.0.1 on 2026-02-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_uniqueancientmeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniqueancientmeta',
            old_name='tiers',
            new_name='tier',
        ),
    ]
