# Generated by Django 6.0.1 on 2026-02-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_rename_tiers_uniqueancientmeta_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueancientmeta',
            name='tier',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
